web/router.ex
defmodule FredIt.Router do
  use FredIt.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end



  scope "/", FredIt do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController do
      post "/comment", PostController, :add_comment
    end
  end

  scope "/auth", FredIt do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

  # Other scopes may use custom stacks.
  # scope "/api", FredIt do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule FredIt.LayoutView do
  use FredIt.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello FredIt!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

    <%= if @current_user do %>
    <div class="container">
      <div class="col-lg-6">
        <h4>Welcome, <%= @current_user.name %>!</h4>
        <img src="<%= @current_user.avatar %>" class="img-circle" width="40" height="40"/>
        <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
    <% else %>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="<%= auth_path @conn, :index, "github" %>">Login</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>
      </div>
        <% end %>

      <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="jumbotron">
        <h2><%= gettext "Welcome to %{name}", name: "FredIt!" %></h2>
        <p class="lead"> On this platform users can share & view Freds <br /> posted for discussion and remove/edit the Freds they created.</p>
      </div>

      <%= if @current_user do %>
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      <% end %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>